name: Update Documentation

on:

  pull_request:

    branches:

      - main

jobs:

  update-doc:

    name: Update Theneo Documentation

    runs-on: ubuntu-latest

    steps:

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout

        uses: actions/checkout@v4

      - name: Setup Node.js

        uses: actions/setup-node@v4

        with:

          node-version: "18"
      - name: Update Documentation on Theneo

        uses: Theneo-Inc/api-documentation@1.8.0

        with:

          FILE_PATH: /Users/marieedelstein/Desktop/API Specs/openapi (7).yaml

          PROJECT_SLUG: github-actions-1

          VERSION_SLUG: <version_slug>

          WORKSPACE_SLUG: mariam-testing

          SECRET: 7063a11a-2a5a-4316-abc2-14edbee51c30


          AUTO_PUBLISH: true

          IMPORT_OPTION: overwrite

          INCLUDE_GITHUB_METADATA: true
